language: python

python:
  - 3.6.9

dist: focal

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y debhelper dh-autoreconf devscripts

script:
    - debuild -i -us -uc -b

notifications:
  email:
    on_success: change
    on_failure: change
