# This workflow will build the package and make a release
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build & Release

on: push

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-20.04]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
          path: readynas-sickchill
      - name: Build Debian package
        run: |
          cd readynas-sickchill
          sudo apt-get -qq update
          sudo apt-get install -y debhelper dh-autoreconf devscripts
          debuild -i -us -uc -b
          mkdir ../artifacts
          mv ../sickchill_20* ../artifacts/
          echo 'Done'
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: artifacts
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}